export const TODO_FETCH_REQUEST =  'TODO_FETCH_REQUEST';
export const TODO_FETCH_SUCCESS =  'TODO_FETCH_SUCCESS';
export const TODO_FETCH_ERROR =  'TODO_FETCH_ERROR';
export const TODO_UPDATE_REQUEST =  'TODO_UPDATE_REQUEST';
export const TODO_DELETE_REQUEST =  'TODO_DELETE_REQUEST';