export const FETCH_SECTION_REQUEST = 'FETCH_SECTION_REQUEST';
export const FETCH_SECTION_SUCCESS = 'FETCH_SECTION_SUCCESS';
export const FETCH_SECTION_FAILD = 'FETCH_SECTION_FAILD';
export const CREATE_SECTION =  'CREATE_SECTION';
